import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css';
import Banner from '../components/Banner/Banner';
import Header from '../components/Header/Header';
import Types from '../components/Types/Types';
import Services from '../components/Services/Services';
import About from '../components/About/About';
import Pricing from '../components/Pricing/Pricing';
import HappyClient from '../components/HappyClient/HappyClient';
import Contact from '../components/Contact/Contact';
import Footer from '../components/Footer/Footer';


export default function Home() {
  return (
    <div >
      <Head>
        <title>Cargo</title>
        <meta name="description" content="Generated by Nazirul Cloud" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header/>
        <Banner/>
        <Types/>
        <Services/>
        <About/>
        <Pricing/>
        <HappyClient/>
        <Contact/>
   
      </main>

      <footer >
      <Footer/>
      </footer>
    </div>
  )
}
